"""Provider-neutral deterministic Today Market Mock application slice."""

from .contracts import (
    ADAPTER_CONTRACT_VERSION,
    DEFAULT_MOCK_ASSUMPTION,
    MOCK_ASSUMPTION_PROFILE_ID,
    OVERALL_LIVE_GATE,
    PLANNING_POLICY_VERSION,
    PROJECTION_VERSION,
    REQUIRED_CAPABILITY_FAMILIES,
    SYNTHETIC_SOURCE_KEY,
    CapabilityFamily,
    CoverageStatus,
    FailureCategory,
    MockPlanningAssumption,
    MockScenario,
    OrchestrationState,
    PlanningState,
    RefreshTrigger,
    Retryability,
    SnapshotReference,
    SourceMode,
    TodayMarketAcquisitionBatch,
    TodayMarketAcquisitionError,
    TodayMarketAcquisitionFailure,
    TodayMarketCoverage,
    TodayMarketDemoProjection,
    TodayMarketFamilyResult,
    TodayMarketRefreshIntent,
    TodayMarketRefreshOutcome,
    TodayMarketRefreshPlan,
    TodayMarketSourceProvenance,
    ValidationStatus,
)
from .fingerprint import canonical_json_bytes, canonical_sha256
from .mock import DeterministicTodayMarketMock, MockUsageState
from .orchestrator import run_mock_refresh
from .planner import AUTOMATIC_SESSION_CEILING, build_refresh_plan
from .port import TodayMarketAcquisitionPort
from .projection import (
    CandidateValidationError,
    build_demo_projection,
    validate_publishable_batch,
)

__all__ = [
    "ADAPTER_CONTRACT_VERSION",
    "AUTOMATIC_SESSION_CEILING",
    "CandidateValidationError",
    "CapabilityFamily",
    "CoverageStatus",
    "DEFAULT_MOCK_ASSUMPTION",
    "DeterministicTodayMarketMock",
    "FailureCategory",
    "MOCK_ASSUMPTION_PROFILE_ID",
    "MockPlanningAssumption",
    "MockScenario",
    "MockUsageState",
    "OVERALL_LIVE_GATE",
    "OrchestrationState",
    "PLANNING_POLICY_VERSION",
    "PROJECTION_VERSION",
    "PlanningState",
    "REQUIRED_CAPABILITY_FAMILIES",
    "RefreshTrigger",
    "Retryability",
    "SYNTHETIC_SOURCE_KEY",
    "SnapshotReference",
    "SourceMode",
    "TodayMarketAcquisitionBatch",
    "TodayMarketAcquisitionError",
    "TodayMarketAcquisitionFailure",
    "TodayMarketAcquisitionPort",
    "TodayMarketCoverage",
    "TodayMarketDemoProjection",
    "TodayMarketFamilyResult",
    "TodayMarketRefreshIntent",
    "TodayMarketRefreshOutcome",
    "TodayMarketRefreshPlan",
    "TodayMarketSourceProvenance",
    "ValidationStatus",
    "build_demo_projection",
    "build_refresh_plan",
    "canonical_json_bytes",
    "canonical_sha256",
    "run_mock_refresh",
    "validate_publishable_batch",
]
